### ISSUE TITLE
best practices / software maintenance guidelines

### ISSUE THREAD

**Issue by kba** [OCR-D/ocrd-website#119]
We had a similar [document prepared for an OCR-D workshop in 2019](https://hackmd.io/g-8QuOAnSQeqnb8PRNjFbQ) whose recommendations should be integrated into the best-practice document.

ht @bertsky

**Comment by bertsky** [comment]
These recommendations are nearly complementary to the current dev-best-practice document. I believe this is rather urgent, since in the next weeks many new collegues will commence work.

BTW, another example for coding guidelines exists [in the Kitodo project](https://www.kitodo.org/fileadmin/groups/kitodo/Dokumente/Kitodo-EntwicklerLeitfaden_2017-06.pdf). They elaborate on branching / PR rules and developer vs. reviewer roles. Also, communicating new efforts on time and updating specs is required here. Plus it makes some remarks on coding style (for Java and PHP). AFAICS we have nothing explicit for Python yet (should at least mention PEP8).

**Comment by bertsky** [comment]
related: #112

**Comment by kba** [comment]
Let's keep discussion in #112 which is closely related.
