### ISSUE TITLE
toc sidebar for GT guidelines

### ISSUE THREAD

**Issue by EEngl52** [OCR-D/ocrd-website#207]
add a toc like https://ocr-d.de/de/gt-guidelines/ as a sidebar to all subpages of the GT guidelines to make their structure clearer

**Comment by bertsky** [comment]
Probably as simple as replacing `partial` with `full` in https://github.com/OCR-D/gt-guidelines/blob/ce1104890dc500c4f72f3145795e832c2c122a0e/en/properties/docs-build-html5_ocrd.properties#L29 (according to [this](https://www.dita-ot.org/dev/parameters/parameters-html5.html#html5__nav-toc)?

**Comment by bertsky** [comment]
Can be closed AFAICS

**Comment by kba** [comment]
Yes, the sidebar is now correctly displayed in the Guidelines.

But  TBH I don't understand why https://ocr-d.de/en/gt-guidelines/ renders like it does, there is no index.html there, just a file `toc.html` and that shouldn't be rendered by DITA not Jekyll. There is some Jekyll trickery going on here. But since the result seems to please people, I'll not investigate further.

@tboenig Maybe have a look whether this is right from your POV once you're back.

**Comment by tboenig** [comment]
If you want to generated the toc file as an index file, you must change the parameter in the 
https://github.com/OCR-D/gt-guidelines/blob/master/de/properties/docs-build-html5_ocrd.properties

# Base name of the Table of Contents file:
args.html5.toc = **index**

But, if you use the dita-ot transformation, you will find an index file in the `trans` directory. This is not the toc file.
