### ISSUE TITLE
`tesserocr-recognize` acts differently when segmenting alone versus segmenting+recognising

### ISSUE THREAD

**Issue by sven-nm** [OCR-D/ocrd-website#215]
It looks like `tesserocr-recognize` yields significantly different results when used :
1) for segmentation and recognition in a single step and 
2) for segmentation in one step and recognition in another.

For instance, the two commands below do not yield the same results (the second being much more prone to errors): 
```shell
# Segmentation and recognition in one step
tesserocr-recognize -I OCR-D-BIN -O OCR-D-SEG -P segmentation_level region -P textequiv_level word -P model eng+grc
```
```shell
# Segmentation step
tesserocr-recognize -I OCR-D-BIN -O OCR-D-REG -P segmentation_level region -P textequiv_level word
# Recognition step
tesserocr-recognize -I OCR-D-REG -O OCR-D-OCR -P segmentation_level none -P model eng+grc
```

Even so the docs mention [here](https://ocr-d.de/en/workflows) and [here](https://github.com/OCR-D/ocrd_tesserocr/blob/master/ocrd_tesserocr/recognize.py) that setting `segmentation_level` to `none` prevents `tesserocr-recognize` from resegmenting, @bertsky suggested in [this thread](https://gitter.im/OCR-D/Lobby?at=609a9ca48096db40c74f302c) that `tesserocr-recognize` would resegment words anyway. In order to avoid confusion, this should maybe be explicitely mentioned in the docs.

**Comment by EEngl52** [comment]
https://github.com/OCR-D/ocrd-website/pull/216

**Comment by bertsky** [comment]
> Even so the docs mention [here](https://ocr-d.de/en/workflows) and [here](https://github.com/OCR-D/ocrd_tesserocr/blob/master/ocrd_tesserocr/recognize.py) that setting `segmentation_level` to `none` prevents `tesserocr-recognize` from resegmenting, @bertsky suggested in [this thread](https://gitter.im/OCR-D/Lobby?at=609a9ca48096db40c74f302c) that `tesserocr-recognize` would resegment words anyway. In order to avoid confusion, this should maybe be explicitely mentioned in the docs.

I'm afraid there was a misunderstanding here. Sorry if I'm late to the discussion and even more so if my initial answer in the chat was confusing. 

Anyway, here's the point: the reason that all-in-one workflow does not yield the same results like this segment-then-recognize workflow is **not** that the latter's recognition step resegments anything (above the glyph level), but rather that it does not. In other words, because it is tied to the word coordinates from the rule-based (Omnifont) segmenter, it cannot reach the same accuracy as the all-in-one workflow, which in contrast is allowed to override the word segmentation via LSTM results.

You should get more similar results between all-in-one and modularized workflows if you picked the _line level_ as point of delivery. But then still results won't be exactly the same, because:
- all-in-one: Tesseract's internal data structures will pass non-overlapping (polygonal) lines to the LSTMs
- modular: the ResultIterator will only give bounding boxes, which may still overlap (but you can try to use `-P shrink_polygons true` against that)
