### ISSUE TITLE
workflow guide: re-sync between website git and wiki git

### ISSUE THREAD

**Issue by bertsky** [OCR-D/ocrd-website#292]
Under `generic data management` we have `dummy processing` (but not in the Wiki) and `adaptation of coordinates` (but in the Wiki only as title).

Also, I'd like to add a new "step" `generic transformation` for `ocrd-page-transform` (and possibly other fixup tasks).

BTW the wiki also has changes that can be synced back already.

**Comment by kba** [comment]
> Under `generic data management` we have `dummy processing` (but not in the Wiki)

I've moved that [section to the wiki](https://github.com/OCR-D/ocrd-website/wiki/Workflow-Guide-dummy-processing)

> and `adaptation of coordinates` (but in the Wiki only as title).

This was a typo, should be `adaptation` not `adaption`, now fixed in home and sidebar, the right link is https://github.com/OCR-D/ocrd-website/wiki/Workflow-Guide-adaptation-of-coordinates

> Also, I'd like to add a new "step" `generic transformation` for `ocrd-page-transform` (and possibly other fixup tasks).

I've prepared this, feel free to edit https://github.com/OCR-D/ocrd-website/wiki/Workflow-Guide-generic-transformations and give me a heads-up when it's ready to publish.

> BTW the wiki also has changes that can be synced back already.

Shall I wait for the "generic transformation" wiki page or sync back now?

**Comment by bertsky** [comment]
> Shall I wait for the "generic transformation" wiki page or sync back now?

I'm done with my changes to the wiki now.

**Comment by kba** [comment]
Fixed in #293
