### ISSUE TITLE
add system requirements to setup guide

### ISSUE THREAD

**Issue by EEngl52** [OCR-D/ocrd-website#78]
At the very beginning of the setup guide there should be some information on the system requirements of the OCR-D-Software. So far this is only specified in the FAQ

**Comment by cneud** [comment]
I could not find any specific info on this in the FAQ, but what else do we require?

```
Minimum
* x86-64 CPU
* 8 GB RAM (more recommended)
* min. 10 GB free disk space for local installation 
  - (min/max similar to Docker?)
* Linux OS
* Python 3.x

Alternatively, use [Docker](https://hub.docker.com/u/ocrd)
```

**Comment by kba** [comment]
> x86-64 CPU

Since most of the software is Python-based, that is not hard requirement. Not all the dependencies might have prebuilt packages for all platforms but in theory, I see no reason why e.g. RISC architectures wouldn't work.

> Python 3.x

For now: Python 3.5+ but that is close to end-of-life now (security fixes only, until September 2020), so better 3.6 or 3.7. Though not 3.8 because there's still many packages unavailable for it and @stweil reported issues with not being able to run 3.7 and 3.8 side-by-side in Debian

> Linux OS

Ubuntu 18.04 is what we will target as a platform for the time being. As long as Python is installed (with the limitations outlined above) and essential build tools are available (gcc, make, autotools), ocrd_all can be built on most Linux platforms. Ubuntu or Debian (and variants) are recommended because the documentation is largely accurate for those as well.

> * min. 10 GB free disk space for local installation 

With models (think anybaseocr's 800MB dewarping model), temporary data (e.g. cached download of tensorflow pypi package is ~530MB) and Docker image size (~7GB for max/2020-xx-xx image), it's probably wise to recommend something much higher, like 100 GB. Otherwise users might provision too small a hard disk for virtual servers (been there myself...)

**Comment by bertsky** [comment]
The note on (un)supported Python versions is very urgent IMHO. There's to date no place in setup guide, user guide, dev guide or ocrd_all README which states the above facts.

And maybe we should also add a large and friendly note what we **recommend** as platform for early adopters and developers. We have seen people struggly with Ubuntu 19 and 20 (due to Python 3.8) in recent months. So we should not say "Ubuntu 18 or higher", but let's be clear: we should recommend Ubuntu 18 for native installation (while stating which others _should work in principle_), but Docker containers beyond that.

**Comment by EEngl52** [comment]
see https://github.com/OCR-D/ocrd-website/pull/122

**Comment by kba** [comment]
c.f. https://ocr-d.de/en/setup#system-requirements
